server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  flyway:
    username: root
    password: root
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"